<?php
declare(strict_types=1);
session_start();
require_once __DIR__ . '/../lib/security.php';
require_once __DIR__ . '/../lib/db.php';
aj360_require_admin();
$mysqli = db(); $adminId = (int)$_SESSION['aj360_admin_id'];
$stmt = $mysqli->prepare('SELECT ip_address, device_id, user_agent, location, login_at FROM admin_login_logs WHERE admin_id=? ORDER BY login_at DESC LIMIT 50'); $stmt->bind_param('i', $adminId); $stmt->execute(); $logs = $stmt->get_result();
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Login Activity | AssamJobs360 Admin</title><link href="<?= aj360_h(aj360_url('assets/vendor/bootstrap/bootstrap.min.css')) ?>" rel="stylesheet"><link href="<?= aj360_h(aj360_url('assets/admin.css')) ?>" rel="stylesheet"></head><body class="admin-page"><main class="container py-4"><div class="admin-topbar d-flex justify-content-between align-items-center"><div><div class="admin-kicker">PROFILE SECURITY</div><h1>Login Activity</h1></div><a class="btn btn-sm" href="<?= aj360_h(aj360_url('admin/profile.php')) ?>">Back to Profile</a></div><section class="card border-0 shadow-sm"><div class="card-body"><p class="small text-muted">Your last 50 successful administrator logins.</p><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Date & Time</th><th>IP Address</th><th>Location</th><th>Device ID</th><th>Browser / Device</th></tr></thead><tbody><?php while ($log = $logs->fetch_assoc()): ?><tr><td><?= aj360_h(date('d M Y, h:i A', strtotime((string)$log['login_at']))) ?></td><td><?= aj360_h($log['ip_address']) ?></td><td><?= aj360_h($log['location'] ?: 'Unavailable') ?></td><td><code class="small"><?= aj360_h(substr($log['device_id'], 0, 16)) ?>…</code></td><td class="small text-muted" style="max-width:280px;white-space:normal"><?= aj360_h($log['user_agent'] ?: 'Unknown') ?></td></tr><?php endwhile; ?></tbody></table></div></div></section></main><?php require __DIR__ . '/partials/session_timeout.php'; ?></body></html>
