<?php
declare(strict_types=1);
$metaTitle = 'Assam Government Jobs, Admit Card, Results & Mock Tests | AssamJobs360';
$metaDescription = 'Find latest Assam government jobs, admit cards, results and mock tests with quick eligibility and deadlines.';
$cats = ['APSC','ADRE','Assam Police','DHS','DME','APDCL','NHM','Forest','Judiciary','Railway','Banking','SSC','UPSC','Indian Army','Assam Rifles'];
ob_start();
?>
<div class="home-page">
  <section class="hero-section">
    <div class="hero-copy"><span class="eyebrow">ASSAM'S TRUSTED JOB PORTAL</span><h1>Find the right government job, <span>faster.</span></h1><p>Latest Assam job notifications, admit cards, results and verified official application links—all in one place.</p><div class="hero-highlights"><span>✓ Verified official links</span><span>✓ Daily job updates</span><span>✓ Free mock tests</span></div></div>
    <div class="hero-stat-card"><div><i>AJ</i><span><strong>Daily updates</strong><small>Never miss an opportunity</small></span></div><hr><div class="d-flex gap-4"><span><b>15+</b><small>Categories</small></span><span><b>100%</b><small>Free access</small></span></div></div>
  </section>
  <section class="search-panel"><div class="search-panel-title"><span class="search-icon">⌕</span><span><strong>Search Jobs</strong><small>Find vacancies that match your profile</small></span></div><form class="row g-2" method="get" action="<?= aj360_h(aj360_url()) ?>"><input type="hidden" name="p" value="jobs"><div class="col-6 col-lg"><input name="department" class="form-control" placeholder="Department"></div><div class="col-6 col-lg"><input name="qualification" class="form-control" placeholder="Qualification"></div><div class="col-6 col-lg"><input name="district" class="form-control" placeholder="District"></div><div class="col-6 col-lg"><input name="category" class="form-control" placeholder="Category"></div><div class="col-12 col-lg-auto d-grid"><button class="btn btn-search">Search Jobs →</button></div></form></section>
  <section class="quick-links"><a href="<?= aj360_h(aj360_url('/', ['p'=>'admit-card'])) ?>"><span>▣</span>Admit Card</a><a href="<?= aj360_h(aj360_url('/', ['p'=>'results'])) ?>"><span>✓</span>Results</a><a href="<?= aj360_h(aj360_url('/', ['p'=>'syllabus'])) ?>"><span>▤</span>Syllabus</a><a href="<?= aj360_h(aj360_url('/', ['p'=>'mock-tests'])) ?>"><span>◉</span>Mock Tests</a><a href="<?= aj360_h(aj360_url('/', ['p'=>'current-affairs'])) ?>"><span>◷</span>Current Affairs</a></section>
  <section class="content-section"><div class="section-heading"><div><span class="eyebrow">EXPLORE OPPORTUNITIES</span><h2>Popular Job Categories</h2></div><a href="<?= aj360_h(aj360_url('/', ['p'=>'jobs'])) ?>">View all jobs →</a></div><div class="category-grid"><?php foreach ($cats as $index => $category): ?><a class="category-chip" href="<?= aj360_h(aj360_url('/', ['p'=>'jobs','category'=>$category])) ?>"><span><?= str_pad((string)($index + 1), 2, '0', STR_PAD_LEFT) ?></span><?= aj360_h($category) ?><b>→</b></a><?php endforeach; ?></div></section>
  <section class="content-section latest-section"><div class="section-heading"><div><span class="eyebrow">FRESH NOTIFICATIONS</span><h2>Latest Jobs</h2></div><a href="<?= aj360_h(aj360_url('/', ['p'=>'jobs'])) ?>">View all jobs →</a></div><div class="row g-3"><?php require_once __DIR__ . '/../lib/db.php'; $res = db()->query("SELECT job_name, department, qualification, age_limit, salary, last_date, job_slug FROM jobs ORDER BY last_date ASC LIMIT 8"); if ($res->num_rows === 0): ?><div class="col-12"><div class="empty-jobs">New job notifications will appear here shortly.</div></div><?php else: while ($row = $res->fetch_assoc()): ?><div class="col-12 col-md-6"><article class="job-card"><div class="job-card-top"><span class="department-tag"><?= aj360_h($row['department']) ?></span><span class="deadline">Last date: <?= aj360_h($row['last_date'] ?: 'TBA') ?></span></div><h3><?= aj360_h($row['job_name']) ?></h3><div class="job-meta"><span>Qualification: <b><?= aj360_h($row['qualification']) ?></b></span><span>Age: <b><?= aj360_h($row['age_limit'] ?: 'As per rules') ?></b></span></div><div class="job-card-bottom"><span><?= aj360_h($row['salary'] ?: 'Salary as per rules') ?></span><a href="<?= aj360_h(aj360_url('/', ['p'=>'job','job_slug'=>(string)$row['job_slug']])) ?>">View details →</a></div></article></div><?php endwhile; endif; ?></div></section>
</div>
<?php $content = ob_get_clean(); require __DIR__ . '/layout.php';
