<?php
declare(strict_types=1);
require_once __DIR__ . '/../lib/db.php';
require_once __DIR__ . '/../lib/security.php';
require_once __DIR__ . '/../lib/user_security.php';
aj360_require_user();
$metaTitle = 'Free Assam Mock Tests | AssamJobs360';

$metaDescription = 'Practice Assam government exam questions with a timer, answer review and score analysis.';
$mysqli = db(); $testId = (int)($_GET['test'] ?? 0); $view = (string)($_GET['view'] ?? 'list');

if ($view === 'result' && $_SERVER['REQUEST_METHOD'] === 'POST' && $testId > 0) {
    aj360_verify_csrf((string)($_POST['csrf'] ?? ''));
    $stmt = $mysqli->prepare('SELECT q.id, q.question_text, a.correct_option_ids, a.explanation FROM questions q JOIN answers a ON a.question_id = q.id WHERE q.mock_test_id = ?'); $stmt->bind_param('i', $testId); $stmt->execute(); $questions = $stmt->get_result()->fetch_all(MYSQLI_ASSOC); $submitted = $_POST['answer'] ?? [];
    $correct = 0; $wrong = 0; $unanswered = 0;
    foreach ($questions as &$question) { $selected = isset($submitted[$question['id']]) ? (int)$submitted[$question['id']] : 0; $ids = json_decode((string)$question['correct_option_ids'], true) ?: []; $question['selected'] = $selected; $question['correct'] = $selected > 0 && in_array($selected, array_map('intval', $ids), true); if (!$selected) $unanswered++; elseif ($question['correct']) $correct++; else $wrong++; } unset($question); $score = $correct - ($wrong * .25); ob_start(); ?>
    <div class="test-page py-4"><a class="back-link" href="<?= aj360_h(aj360_url('/', ['p'=>'mock-tests'])) ?>">&larr; All mock tests</a><section class="score-panel"><span>Your Score</span><strong><?= number_format($score, 2) ?></strong><p><?= $correct ?> correct &middot; <?= $wrong ?> wrong &middot; <?= $unanswered ?> unanswered</p><a class="btn btn-light btn-sm" href="<?= aj360_h(aj360_url('/', ['p'=>'mock-tests','test'=>$testId])) ?>">Retake test</a></section><h1 class="test-title">Answer Analysis</h1><?php foreach ($questions as $index => $question): ?><article class="analysis-card <?= $question['correct'] ? 'is-correct' : ($question['selected'] ? 'is-wrong' : '') ?>"><b>Question <?= $index + 1 ?></b><p><?= nl2br(aj360_h($question['question_text'])) ?></p><small><?= $question['correct'] ? 'Correct answer' : 'Incorrect or unanswered' ?><?= $question['explanation'] ? ' — '.aj360_h($question['explanation']) : '' ?></small></article><?php endforeach; ?></div>
    <?php $content = ob_get_clean(); require __DIR__ . '/layout.php'; exit;
}

if ($testId > 0) {
    $stmt = $mysqli->prepare('SELECT id, title, exam_category FROM mock_tests WHERE id = ? LIMIT 1'); $stmt->bind_param('i', $testId); $stmt->execute(); $test = $stmt->get_result()->fetch_assoc();
    $stmt = $mysqli->prepare('SELECT id, question_text, difficulty FROM questions WHERE mock_test_id = ? ORDER BY RAND()'); $stmt->bind_param('i', $testId); $stmt->execute(); $questions = $stmt->get_result()->fetch_all(MYSQLI_ASSOC);
    foreach ($questions as &$question) { $stmt = $mysqli->prepare('SELECT id, option_text FROM options WHERE question_id = ? ORDER BY RAND()'); $stmt->bind_param('i', $question['id']); $stmt->execute(); $question['options'] = $stmt->get_result()->fetch_all(MYSQLI_ASSOC); } unset($question);
    if (!$test || !$questions) { header('Location: '.aj360_url('/', ['p'=>'mock-tests'])); exit; } $csrf = aj360_csrf_token(); $duration = max(5, count($questions)); ob_start(); ?>
    <div class="test-page py-4"><div class="test-toolbar"><div><a class="back-link" href="<?= aj360_h(aj360_url('/', ['p'=>'mock-tests'])) ?>">&larr; Exit test</a><h1><?= aj360_h($test['title']) ?></h1><span><?= aj360_h($test['exam_category']) ?> &middot; <?= count($questions) ?> questions &middot; -0.25 negative marking</span></div><div class="timer-box">Time left <b id="timer"><?= $duration ?>:00</b></div></div><form method="post" action="<?= aj360_h(aj360_url('/', ['p'=>'mock-tests','test'=>$testId,'view'=>'result'])) ?>" id="testForm"><input type="hidden" name="csrf" value="<?= aj360_h($csrf) ?>"><input type="hidden" name="review" id="reviewState" value=""><div class="test-runner"><aside class="question-palette"><b>Questions</b><div class="palette-grid"><?php foreach ($questions as $index => $question): ?><button type="button" class="palette-btn unanswered" data-question="<?= $index ?>"><?= $index + 1 ?></button><?php endforeach; ?></div><div class="palette-legend"><span><i class="answered"></i> Solved</span><span><i class="unanswered"></i> Not solved</span><span><i class="review"></i> Review later</span></div></aside><div class="question-stack"><?php foreach ($questions as $index => $question): ?><article class="question-card test-question <?= $index === 0 ? 'active' : '' ?>" data-index="<?= $index ?>"><div class="question-number">Question <?= $index + 1 ?> of <?= count($questions) ?> <span><?= aj360_h(ucfirst($question['difficulty'])) ?></span></div><h2><?= nl2br(aj360_h($question['question_text'])) ?></h2><div class="options"><?php foreach ($question['options'] as $optionIndex => $option): ?><label><input type="radio" name="answer[<?= (int)$question['id'] ?>]" value="<?= (int)$option['id'] ?>"><b><?= chr(65 + $optionIndex) ?></b><span><?= aj360_h($option['option_text']) ?></span></label><?php endforeach; ?></div><div class="question-actions"><button type="button" class="btn btn-outline-secondary btn-sm previous">&larr; Previous</button><button type="button" class="btn btn-outline-warning btn-sm review-btn">Mark for Review</button><button type="button" class="btn btn-search next">Next &rarr;</button></div></article><?php endforeach; ?><button class="btn btn-danger submit-test" type="submit">Submit Test</button></div></div></form></div><script>
document.addEventListener('contextmenu', event => event.preventDefault());
document.addEventListener('copy', event => event.preventDefault());
document.addEventListener('cut', event => event.preventDefault());
document.addEventListener('keydown', event => { if ((event.ctrlKey || event.metaKey) && ['c', 'x', 'u', 's', 'p'].includes(event.key.toLowerCase())) event.preventDefault(); });
const form=document.getElementById('testForm'), timer=document.getElementById('timer'), questions=[...document.querySelectorAll('.test-question')], palette=[...document.querySelectorAll('.palette-btn')], review=new Set(); let current=0, seconds=<?= $duration * 60 ?>;
function show(index){current=Math.max(0,Math.min(index,questions.length-1));questions.forEach((q,i)=>q.classList.toggle('active',i===current));palette.forEach((b,i)=>b.classList.toggle('current',i===current));window.scrollTo({top:0,behavior:'smooth'});}
function paint(questionIndex){const q=questions[questionIndex], button=palette[questionIndex], hasAnswer=!!q.querySelector('input:checked');button.className='palette-btn '+(review.has(questionIndex)?'review':(hasAnswer?'answered':'unanswered'));}
questions.forEach((q,i)=>{q.querySelectorAll('input').forEach(input=>input.addEventListener('change',()=>paint(i)));q.querySelector('.next').addEventListener('click',()=>show(i+1));q.querySelector('.previous').addEventListener('click',()=>show(i-1));q.querySelector('.review-btn').addEventListener('click',()=>{review.has(i)?review.delete(i):review.add(i);q.querySelector('.review-btn').textContent=review.has(i)?'Remove Review':'Mark for Review';paint(i);});});palette.forEach((button,i)=>button.addEventListener('click',()=>show(i)));form.addEventListener('submit',()=>document.getElementById('reviewState').value=[...review].join(','));setInterval(()=>{seconds--;timer.textContent=Math.max(0,Math.floor(seconds/60))+':'+String(Math.max(0,seconds%60)).padStart(2,'0');if(seconds<=0)form.submit()},1000);show(0);
    </script>
    <?php $content = ob_get_clean(); require __DIR__ . '/layout.php'; exit;
}
$tests = $mysqli->query('SELECT mt.id, mt.title, mt.exam_category, COUNT(q.id) AS question_count FROM mock_tests mt LEFT JOIN questions q ON q.mock_test_id = mt.id GROUP BY mt.id ORDER BY mt.created_at DESC')->fetch_all(MYSQLI_ASSOC); ob_start(); ?>
<div class="test-page py-4"><section class="mock-hero"><span class="eyebrow">PRACTICE. ANALYSE. IMPROVE.</span><h1>Free Assam Mock Tests</h1><p>Prepare with exam-style questions, time limits and instant detailed score analysis.</p></section><div class="section-heading mt-4"><div><span class="eyebrow">START PRACTICING</span><h2>Available Tests</h2></div></div><div class="row g-3"><?php if (!$tests): ?><div class="col-12"><div class="empty-jobs">No mock tests are published yet. Add questions from the database to start a test.</div></div><?php else: foreach ($tests as $test): ?><div class="col-12 col-md-6"><article class="test-card"><span><?= aj360_h($test['exam_category']) ?></span><h2><?= aj360_h($test['title']) ?></h2><p><?= (int)$test['question_count'] ?> questions &middot; <?= max(5, (int)$test['question_count']) ?> minutes &middot; -0.25 negative marking</p><a class="btn btn-search" href="<?= aj360_h(aj360_url('/', ['p'=>'mock-tests','test'=>(int)$test['id']])) ?>">Start Test &rarr;</a></article></div><?php endforeach; endif; ?></div></div>
<?php $content = ob_get_clean(); require __DIR__ . '/layout.php';
